apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 2  # Quantidade de réplicas da aplicação
  selector:
    matchLabels:
      app: payment  # Seleciona pods com essa label
  template:
    metadata:
      labels:
        app: payment  # Associa esse label ao pod criado
    spec:
      containers:
      - name: payment
        image: edsontecno/payment:latest  # Imagem do Node.js 
        ports:
        - containerPort: 8080  # Porta exposta pela aplicação
        resources:
          requests:   # Recursos mínimos para cada pod
            memory: "200Mi"
            cpu: "100m"
          limits:     # Limites máximos para cada pod
            memory: "1024Mi"
            cpu: "1"        
        env:
        - name: MERCADOPAGO_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mercadopago_token  
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db        
        - name: AWS_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: aws_accesskey  
        - name: AWS_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: aws_secretkey
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: aws_accesskey  
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: aws_secretkey      
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: session_token       
        - name: URL_PEDIDO
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pedido  
