apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment  # Conecta-se ao pod do backend
  ports:
    - protocol: TCP
      port: 3002  # Porta que será exposta externamente
      targetPort: 8080  # Porta do container
  type: LoadBalancer  # Expor a aplicação externamente através de um LoadBalancer
