package br.com.fiap.microservice_payment.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.mercadopago.resources.payment.Payment;
import lombok.*;
import org.springframework.data.annotation.Id;

import java.math.BigDecimal;

@DynamoDBTable(tableName = "Payment")
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PaymentEntity {

    @Id
    private String id;
    private String operationType;
    private String status;
    private String statusDetail;
    private BigDecimal transactionAmount;

    private String qrCode;
    private String qrCodeBase64;
    private String ticketUrl;
    private String issuerId;
    private String paymentMethodId;

    public static PaymentEntity of(Payment payment) {
        return PaymentEntity.builder()
                .id(payment.getId().toString())
                .operationType(payment.getOperationType())
                .status(payment.getStatus())
                .statusDetail(payment.getStatusDetail())
                .qrCode(payment.getPointOfInteraction().getTransactionData().getQrCode())
                .qrCodeBase64(payment.getPointOfInteraction().getTransactionData().getQrCodeBase64())
                .ticketUrl(payment.getPointOfInteraction().getTransactionData().getTicketUrl())
                .transactionAmount(payment.getTransactionAmount())
                .issuerId(payment.getIssuerId())
                .paymentMethodId(payment.getPaymentMethodId())
                .build();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getOperationType() {
        return operationType;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public String getStatusDetail() {
        return statusDetail;
    }

    @DynamoDBAttribute
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    @DynamoDBAttribute
    public String getQrCode() {
        return qrCode;
    }

    @DynamoDBAttribute
    public String getQrCodeBase64() {
        return qrCodeBase64;
    }

    @DynamoDBAttribute
    public String getTicketUrl() {
        return ticketUrl;
    }

    @DynamoDBAttribute
    public String getIssuerId() {
        return issuerId;
    }

    @DynamoDBAttribute
    public String getPaymentMethodId() {
        return paymentMethodId;
    }
}
